services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production

      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      CONTACT_TO: ${CONTACT_TO}
      CONTACT_FROM: ${CONTACT_FROM}
    ports:
      - "3000:3000"
